language: bash

cache:
    apt: true

install:
  - sudo apt-get install clamav
  - sudo freshclam

before_script:
  - find ci -type f -iname "*.sh" -exec chmod +x {} \;

script:
  - sudo ./ci/scan.sh static
  - sudo ./ci/scan.sh public
